### ISSUE TITLE
osx-arm64 build?

### ISSUE THREAD

**Issue by adamgayoso** [conda-forge/dm-tree-feedstock#16]
It would be great to have a build available for this architecture. 

I made a PR here: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2588

as per the instructions here: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock

**Comment by maresb** [comment]
Thanks @adamgayoso! Looks like you are already well underway.

Do you know how to work with bazel? (Unfortunately I'm useless in this regard.) In case you haven't seen it yet, you may want to have a look here: https://github.com/conda-forge/dm-tree-feedstock/pull/14

**Comment by maresb** [comment]
The PR from the migrator will hopefully arrive within the next few hours.

**Comment by maresb** [comment]
@adamgayoso here it is: https://github.com/conda-forge/dm-tree-feedstock/pull/17

Unfortunately it most likely needs some work.

**Comment by adamgayoso** [comment]
Hi @maresb unfortunately I don't have bandwidth (or knowledge of bazel) to be helpful. I thought I'd just get it started.

**Comment by maresb** [comment]
Ok, no worries, at least it's ready for the next person who comes along.

Since we now have the open PR, I'll close this issue since I don't really think we have any relevant info here. In case you disagree, let me know and I'll reopen this.
